DROP TABLE IF EXISTS matches;

CREATE TABLE matches(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  player1 TEXT NOT NULL,
  player2 TEXT NOT NULL,
  matchID TEXT NOT NULL,
  board INTEGER
);
