DROP TABLE IF EXISTS boards;

CREATE TABLE boards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  index0 INTEGER NOT NULL DEFAULT 0,
  index1 INTEGER NOT NULL DEFAULT 0,
  index2 INTEGER NOT NULL DEFAULT 0,
  index3 INTEGER NOT NULL DEFAULT 0,
  index4 INTEGER NOT NULL DEFAULT 0,
  index5 INTEGER NOT NULL DEFAULT 0,
  index6 INTEGER NOT NULL DEFAULT 0,
  index7 INTEGER NOT NULL DEFAULT 0,
  index8 INTEGER NOT NULL DEFAULT 0,
  match TEXT REFERENCES matches(id)
);

DROP TABLE IF EXISTS matches;

CREATE TABLE matches(
  id TEXT PRIMARY KEY,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  player1 TEXT NOT NULL,
  player2 TEXT NOT NULL,
);

DROP TABLE IF EXISTS policy;

CREATE TABLE policy (
  id INTEGER PRIMARY KEY,
  val0 REAL DEFAULT NULL,
  val1 REAL DEFAULT NULL,
  val2 REAL DEFAULT NULL,
  val3 REAL DEFAULT NULL,
  val4 REAL DEFAULT NULL,
  val5 REAL DEFAULT NULL,
  val6 REAL DEFAULT NULL,
  val7 REAL DEFAULT NULL,
  val8 REAL DEFAULT NULL,
  count0 INTEGER DEFAULT 0,
  count1 INTEGER DEFAULT 0,
  count2 INTEGER DEFAULT 0,
  count3 INTEGER DEFAULT 0,
  count4 INTEGER DEFAULT 0,
  count5 INTEGER DEFAULT 0,
  count6 INTEGER DEFAULT 0,
  count7 INTEGER DEFAULT 0,
  count8 INTEGER DEFAULT 0
);

CREATE UNIQUE INDEX state_idx ON policy(state);
